# Generated by Django 4.0.2 on 2022-03-20 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='Anonymní', max_length=50)),
                ('comment', models.CharField(max_length=1000)),
                ('ratings', models.IntegerField(verbose_name=((1, 1), (2, 2), (3, 3), (4, 4), (5, 5)))),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.food')),
            ],
        ),
    ]
