# Generated by Django 4.0.2 on 2022-03-24 23:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_review_user_food_upload_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='food',
            new_name='food_key',
        ),
        migrations.AddField(
            model_name='review',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
