# Generated by Django 4.0.2 on 2022-03-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_food_review_food_key_review_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
